language: php

php:
   - '5.6'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --optimize-autoloader

script:
  - ./vendor/bin/phpcs --colors -p

before_deploy:
  - php ./tools/make-release.php

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  overwrite: true
  file: 
    - "singlesignon.tar.gz"
    - "singlesignon.zip"
  skip_cleanup: true
  on:
    tags: true